#!/usr/bin/python

# Author: Markus Sachs <m.sachs@allforit.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# set default value of variable (user can override in main.mk)


snmp_info["beronet_info"] = ( ".1.3.6.1.4.1.29886.0", [ "2.0", "3.0", "4.0", "5.0", "6.0" ] )


def inventory_beronet_info(info):
	yield "Info",None
	return

def check_beronet_info(item, params, info):
	for line in info:
		serial = line[0]
		hwrevision = line[1]
		rootfs = line[2]
		firmware = line[3]
		ffpga = line[4]

	 	return 0, "Seriennummer: "+serial+" HW-Revision: "+hwrevision+" RootFS: "+rootfs+" Firmware: "+firmware+" FFPGA: "+ffpga

check_info["beronet_info"] = {
    "check_function"        : check_beronet_info,
    "inventory_function"    : inventory_beronet_info,
    "service_description"   : "Beronet",
    "snmp_info"             : ( '.1.3.6.1.4.1.29886.0.2', [ 0 ] ),
    "snmp_scan_function"    : lambda oid: "berofix voip gateway" in oid(".1.3.6.1.2.1.1.1.0").lower() and  oid('.1.3.6.1.4.1.29886.0.2.0') != None,
}
