#!/usr/bin/python
snmp_info["beronet_cpu_load"] = ( ".1.3.6.1.4.1.29886.0.11.1.1.1", [ "0" ] )
beronet_cpu_load_default_values = (80, 90)

def inventory_beronet_cpu_load(info):
	yield "Load","beronet_cpu_load_default_values"
	return

def check_beronet_cpu_load(item, params, info):
	warn,crit = params
	for line in info:
		cpuload = int(line[0])
		perfdata = [ ( "Cpuload", cpuload, warn, crit ) ]
		if cpuload > crit:
			return 2, "CRIT - CPU Load "+str(cpuload)+" %",perfdata
		elif cpuload > warn:
			return 1, "WARN - CPU Load "+str(cpuload)+" %",perfdata
		else:
			return 0, "OK - CPU Load "+str(cpuload)+" %",perfdata

check_info["beronet_cpu_load"] = {
    "check_function"        : check_beronet_cpu_load,
    "inventory_function"    : inventory_beronet_cpu_load,
    "service_description"   : "Beronet CPU",
	'has_perfdata'			: True,
    "snmp_scan_function"    : lambda oid: "berofix voip gateway" in oid(".1.3.6.1.2.1.1.1.0").lower() and oid('.1.3.6.1.4.1.29886.0.11.1.1.1.0') != None,
}
